name: PROD Despliegue Api Persona

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ZeuzPersonasApi
  AZURE_WEBAPP_PACKAGE_PATH: './PersonasAPI'
  DOTNET_VERSION: '8.0.x'
  AZURE_WEBAPP_RUNTIME: 'dotnet:8'
  AZURE_WEBAPP_OS: 'windows'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore
      run: dotnet restore ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Build
      run: dotnet build ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} -c Release -o ${{env.DOTNET_ROOT}}/myapp
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp
        runtime-stack: ${{ env.AZURE_WEBAPP_RUNTIME }}
        os-type: ${{ env.AZURE_WEBAPP_OS }}